import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Stream TV and Movies Live and Onlin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.hulu.com/static/favicon.ico.png" />
      </Head>
    </div>
  )
}
